[package]
name = "RNFTs"
version = "1.0.0"
authors = []

[addresses]
RNFTs = "0x3d197d2307d1cfdf3ced702d4a36a19dc19c6f986e41a34cbd5ae2550375a24e"

[dev-addresses]

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
#set all_proxy=socks5://127.0.0.1:10808
#$env:all_proxy="socks5://127.0.0.1:10808"